site_name: Allure AI Documentation
theme:
  name: material
  logo: assets/logo.svg
  font:
    text: Nunito Sans
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 'index.md'
  - 'Dashboard':
    - 'dashboard/index.md'
  - 'Widgets':
    - 'Skincare Analyzer': 
      - 'Introduction': 'widgets/skincare/index.md'
      - 'widgets/skincare/configure.md'
      - 'widgets/skincare/embed.md'
    - 'AR Makeup Try-on': 
      - 'Introduction': 'widgets/ar-makeup/index.md'
      - 'widgets/ar-makeup/embed.md'
    - 'Foundation Shade Finder':
      - 'Introduction': 'widgets/foundation/index.md'
      - 'widgets/foundation/embed.md'
    - 'Main Menu':
      - 'Introduction': 'widgets/menu/index.md'
      - 'widgets/menu/embed.md'
  - 'Business Suite API':
    - 'API Reference': 'https://api-business-docs.allure.id/'
  - 'SDK':
    - 'Node.js': 
      - 'Setup': 'sdk/node/index.md'
      - 'Beauty Product Database': 'sdk/node/bpd.md'
      - 'Facial Check Service': 'sdk/node/facial-check-service.md'
      - 'Product Suitability Service': 'sdk/node/product-suitability-service.md'
      - 'Widget Service': 'sdk/node/widget-service.md'
